Improving migrations items controller
sevolchenko/items-delivery-demo pull request #5
Opened 2024-11-19 16:41 UTC by AleksandrLedenev

2024-11-19 16:42 UTC, AleksandrLedenev commented on items-controller/src/main/resources/migrations/init-db/create_items_table.sql
>      type            varchar(255)             not null,
какое значение по умолчанию в type закидывать?

2024-11-19 22:31 UTC, sevolchenko requested changes

2024-11-19 22:31 UTC, sevolchenko commented on items-controller/src/main/resources/migrations/init-db/create_items_table.sql
> +    updated_at      timestamp         null     default NOW(),
Это по дефолту null

2024-11-19 22:31 UTC, sevolchenko commented on items-controller/src/main/kotlin/ru/tbank/itemsdeliverydemo/itemscontroller/item/adapter/rest/dto/ReserveItemResponse.kt
> +import java.util.*
Звездочка называется Wildcard import. IDEA тебе по дефолту ее ставит, если из пакета больше 5 импортов. Нагугли эту настройку и поставь этот порог в 9999.

Это прост плохая практика

Касается всех мест, где это появилось

2024-11-19 22:52 UTC, sevolchenko requested changes

2024-11-19 22:52 UTC, sevolchenko commented on items-controller/src/main/kotlin/ru/tbank/itemsdeliverydemo/itemscontroller/item/adapter/rest/dto/ReserveItemResponse.kt
> +
Тут лишняя строка!

Пока detekt не работает, как ожидалось

В будущем он сам такое фиксить будет

2024-11-20 08:07 UTC, sevolchenko commented on items-controller/src/main/resources/migrations/init-db/create_items_table.sql
>      type            varchar(255)             not null,
Никакое

2024-11-20 08:13 UTC, sevolchenko requested changes

2024-11-20 08:13 UTC, sevolchenko commented on items-controller/src/main/resources/migrations/init-db/create_items_table.sql
> +    status          varchar(255)      not null default 'AVAILABLE',
Я сейчас подумал и понял, что AVAILABLE по-дефолту - это бизнес логика. Пусть она будет на уровне приложения

2024-11-20 13:54 UTC, sevolchenko approved these changes

2024-11-20 13:54 UTC, merged